<?php

namespace Tlapnet\Report\Bridges\Tracy\Panel;

use Tracy\Dumper;

?>
<h1>Reports (<?=count($items)?>)</h1>

<div class="tracy-inner" style="max-width: 900px;">
    <table>
        <tr>
            <th>Report</th>
            <th>Subreport</th>
            <th>DataSource</th>
            <th>Renderer</th>
        </tr>
        <?php foreach ($items as $item) { ?>
        <tr>
            <td><?=$item->report?></td>
            <td><?=$item->subreport?></td>
            <td>
                <?php if ($item->datasource->created === TRUE): ?>
                    <?= Dumper::toHtml($item->datasource->service, [Dumper::COLLAPSE => TRUE, Dumper::LIVE => TRUE]); ?>
                <?php else: ?>
                    <code><?= htmlSpecialChars($item->datasource->type) ?></code>
                <?php endif ?>
            </td>
            <td>
                <?php if ($item->renderer->created === TRUE): ?>
                    <?= Dumper::toHtml($item->renderer->service, [Dumper::COLLAPSE => TRUE, Dumper::LIVE => TRUE]); ?>
                <?php else: ?>
                    <code><?= htmlSpecialChars($item->renderer->type) ?></code>
                <?php endif ?>
            </td>
        </tr>
        <?php } ?>
    </table>
</div>
